In [6]:
##Basic Tensor Operation
import torch
x=torch.tensor([[1,2,3],[4,5,6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
x=torch.tensor([[1.4,4.5,9,90],[3.1,4.0,1,7]])
print(f"Shape:{x.shape}")

Shape:torch.Size([2, 4])


In [8]:
##Tensor Attributes
print(f"Datatype:{x.dtype}")
print(f"Device:{x.device}")

Datatype:torch.int64
Device:cpu


In [5]:
if torch.cuda.is_available():
    x=x.to('cuda')
print(f"Device after moving:{x.device}")


Device after moving:cpu


In [9]:
##Types of Tensors
zeros=torch.zeros(3,3)
ones=torch.ones(3,3)
identity=torch.eye(3)
print(zeros,ones,identity)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [11]:
##Random and Arange Tensors
random=torch.rand(2,4)
arrange=torch.arange(0,8,2)
print(random,arrange)

tensor([[0.4646, 0.6782, 0.5327, 0.2238],
        [0.2772, 0.6540, 0.2814, 0.9269]]) tensor([0, 2, 4, 6])


In [12]:
##Changing Tensor Datatype
x=torch.tensor([9,8,1,3],dtype=torch.float64)
print(x,x.dtype)

tensor([9., 8., 1., 3.], dtype=torch.float64) torch.float64


In [14]:
##.to() Method
x=torch.tensor([1.5,2.5,3.5])
xd=x.to(torch.float64)
print(xd,xd.dtype)

tensor([1.5000, 2.5000, 3.5000], dtype=torch.float64) torch.float64


In [15]:
##.type() Method
x=torch.tensor([1,2,3])
xf=x.type(torch.float32)
print(xf)
print(xf.dtype)

tensor([1., 2., 3.])
torch.float32


In [16]:
##.half() Method
x=torch.tensor([1,2,2])

xh=x.half()
print(xh)

##.float() type
xf=x.float()
print(xf)

##.double() Method
xd=x.double()
print(xd)

##.int() Method
xi=x.int()
print(xi)

##.bool() Method
xb=x.bool()
print(xb)


tensor([1., 2., 2.], dtype=torch.float16)
tensor([1., 2., 2.])
tensor([1., 2., 2.], dtype=torch.float64)
tensor([1, 2, 2], dtype=torch.int32)
tensor([True, True, True])
