Selecting Data (Indexing) in PyTorch

Basic Indexing and Slicing

In [1]:
#Indexing a 1D Tensor
import torch

tensor = torch.tensor([10, 20, 30, 40, 50])
print("Original Tensor:", tensor)

print("First element:", tensor[0])
print("Last element:", tensor[-1])


Original Tensor: tensor([10, 20, 30, 40, 50])
First element: tensor(10)
Last element: tensor(50)


In [2]:
#Indexing a 2D Tensor (Matrices)
tensor_2d = torch.tensor([[1, 2, 3], 
                           [4, 5, 6], 
                           [7, 8, 9]])

print("Element at row=1, col=2:", tensor_2d[1, 2])  # 6


Element at row=1, col=2: tensor(6)


In [3]:
#Slicing a Tensor
# Select first two rows
print("First two rows:\n", tensor_2d[:2, :])

# Select last two columns
print("Last two columns:\n", tensor_2d[:, 1:])


First two rows:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Last two columns:
 tensor([[2, 3],
        [5, 6],
        [8, 9]])


Advanced Indexing in PyTorch

In [4]:
#Boolean Indexing
tensor = torch.tensor([10, 20, 30, 40, 50])
mask = tensor > 25  
filtered_tensor = tensor[mask]
print("Filtered Tensor:", filtered_tensor)


Filtered Tensor: tensor([30, 40, 50])


In [5]:
#Indexing with Tensors (Fancy Indexing)
tensor = torch.tensor([10, 20, 30, 40, 50])
indices = torch.tensor([0, 2, 4])  
selected_elements = tensor[indices]
print("Selected Elements:", selected_elements)


Selected Elements: tensor([10, 30, 50])


In [6]:
#Selecting Non-Contiguous Elements
tensor = torch.tensor([10, 20, 30, 40, 50])
print("Every second element:", tensor[::2])


Every second element: tensor([10, 30, 50])


In [7]:
#Selecting Multiple Rows or Columns
tensor_2d = torch.tensor([[1, 2, 3], 
                           [4, 5, 6], 
                           [7, 8, 9]])

# Select first and third rows
rows = torch.tensor([0, 2])
selected_rows = tensor_2d[rows, :]
print("Selected Rows:\n", selected_rows)


Selected Rows:
 tensor([[1, 2, 3],
        [7, 8, 9]])


Modifying Tensors Using Indexing

In [8]:
#Modifying Tensor Elements
tensor = torch.tensor([10, 20, 30, 40, 50])
tensor[1:3] = torch.tensor([100, 200])  
print("Modified Tensor:", tensor)


Modified Tensor: tensor([ 10, 100, 200,  40,  50])
