In [1]:
##Indexing a Tensor
import torch

x = torch.tensor([[10, 20, 30], [40, 50, 60]])

print(x[0])      # Access first row → tensor([10, 20, 30])
print(x[1, 2])   # Access element at (1,2) → tensor(60)


tensor([10, 20, 30])
tensor(60)


In [2]:
##Slicing a Tensor
print(x[:, 1])   # Selects all rows, second column → tensor([20, 50])
print(x[0, :])   # Selects first row → tensor([10, 20, 30])


tensor([20, 50])
tensor([10, 20, 30])


In [3]:
## .view() vs .reshape()
x = torch.arange(6)  # tensor([0, 1, 2, 3, 4, 5])

y = x.view(2, 3)     # Reshape into (2x3)
print(y)

z = x.reshape(3, 2)  # Reshape into (3x2)
print(z)


tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [4]:
##Concatenation (torch.cat())
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

c = torch.cat((a, b), dim=0)  # Concatenate along rows
print(c)

d = torch.cat((a, b), dim=1)  # Concatenate along columns
print(d)


tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [5]:
##Stacking (torch.stack())
e = torch.stack((a, b), dim=0)  
print(e.shape)  # (2,2,2)


torch.Size([2, 2, 2])


In [6]:
##Basic Operations
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

print(x + y)  # tensor([5, 7, 9])
print(x - y)  # tensor([-3, -3, -3])
print(x * y)  # tensor([4, 10, 18])
print(x / y)  # tensor([0.25, 0.4, 0.5])


tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])


In [7]:
##In-place Operations (_ Suffix)
x.add_(y)  # x is modified in-place
print(x)


tensor([5, 7, 9])


In [8]:
##.T (Transpose for 2D Tensors)
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x.T)  # Transposes rows and columns


tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [9]:
##.permute() (Generalized Dimension Change)
x = torch.rand(2, 3, 4)  # Shape: (2, 3, 4)
y = x.permute(2, 0, 1)   # Reorders dimensions
print(y.shape)  # (4, 2, 3)


torch.Size([4, 2, 3])


In [10]:
##.squeeze() (Remove Singleton Dimensions)
x = torch.rand(1, 3, 1, 4)
print(x.shape)  # (1, 3, 1, 4)

y = x.squeeze()
print(y.shape)  # (3, 4)


torch.Size([1, 3, 1, 4])
torch.Size([3, 4])


In [11]:
##.unsqueeze() (Add Singleton Dimensions)
x = torch.tensor([1, 2, 3])
y = x.unsqueeze(0)  # Add a batch dimension
print(y.shape)  # (1, 3)


torch.Size([1, 3])


In [12]:
import torch

# Creating tensors
x = torch.rand(3, 4)
y = torch.rand(3, 4)

# Manipulations
z = torch.cat((x, y), dim=0)
reshaped = x.reshape(4, 3)
permuted = x.permute(1, 0)
squeezed = reshaped.squeeze()

# Output
print("Original Shape:", x.shape)
print("Concatenated Shape:", z.shape)
print("Reshaped Shape:", reshaped.shape)
print("Permuted Shape:", permuted.shape)
print("Squeezed Shape:", squeezed.shape)


Original Shape: torch.Size([3, 4])
Concatenated Shape: torch.Size([6, 4])
Reshaped Shape: torch.Size([4, 3])
Permuted Shape: torch.Size([4, 3])
Squeezed Shape: torch.Size([4, 3])


In [13]:
##How do you concatenate two tensors along a specific dimension?
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

c = torch.cat((a, b), dim=0)  # Concatenate along rows
d = torch.cat((a, b), dim=1)  # Concatenate along columns

print(c)  

print(d)  


tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [14]:
##What is the difference between .contiguous() and .non_contiguous() tensors in PyTorch?
x = torch.rand(3, 4).permute(1, 0)  # Non-contiguous tensor
y = x.contiguous().view(4, 3)  # Now memory is contiguous
