In [3]:
#Finding the Minimum Value
import torch

tensor = torch.tensor([[3, 7, 1], [5, 2, 8], [9, 6, 4]])

min_value = torch.min(tensor)
print("Minimum value:", min_value)

min_col = torch.min(tensor, dim=0)
print("Minimum values along columns:", min_col.values)

min_row = torch.min(tensor, dim=1)
print("Minimum values along rows:", min_row.values)


Minimum value: tensor(1)
Minimum values along columns: tensor([3, 2, 1])
Minimum values along rows: tensor([1, 2, 4])


In [4]:
#Finding the Maximum Value

max_value = torch.max(tensor)
print("Maximum value:", max_value)

max_col = torch.max(tensor, dim=0)
print("Maximum values along columns:", max_col.values)

max_row = torch.max(tensor, dim=1)
print("Maximum values along rows:", max_row.values)


Maximum value: tensor(9)
Maximum values along columns: tensor([9, 7, 8])
Maximum values along rows: tensor([7, 8, 9])


In [5]:
#Computing the Mean (Average)
mean_value = torch.mean(tensor.float())  
print("Mean value:", mean_value)

mean_col = torch.mean(tensor.float(), dim=0)
print("Mean values along columns:", mean_col)

mean_row = torch.mean(tensor.float(), dim=1)
print("Mean values along rows:", mean_row)


Mean value: tensor(5.)
Mean values along columns: tensor([5.6667, 5.0000, 4.3333])
Mean values along rows: tensor([3.6667, 5.0000, 6.3333])


In [6]:
#Computing the Sum
sum_value = torch.sum(tensor)
print("Sum of all elements:", sum_value)

sum_col = torch.sum(tensor, dim=0)
print("Sum along columns:", sum_col)

sum_row = torch.sum(tensor, dim=1)
print("Sum along rows:", sum_row)


Sum of all elements: tensor(45)
Sum along columns: tensor([17, 15, 13])
Sum along rows: tensor([11, 15, 19])


In [7]:
#Handling Multi-Dimensional Tensors
tensor_3d = torch.randint(0, 10, (2, 3, 3))  # Shape: (2, 3, 3)
print("3D Tensor:\n", tensor_3d)

min_dim0 = torch.min(tensor_3d, dim=0).values
max_dim0 = torch.max(tensor_3d, dim=0).values

print("Minimum along dim 0:\n", min_dim0)
print("Maximum along dim 0:\n", max_dim0)


3D Tensor:
 tensor([[[1, 7, 4],
         [8, 0, 1],
         [8, 8, 2]],

        [[2, 3, 6],
         [0, 1, 2],
         [5, 5, 8]]])
Minimum along dim 0:
 tensor([[1, 3, 4],
        [0, 0, 1],
        [5, 5, 2]])
Maximum along dim 0:
 tensor([[2, 7, 6],
        [8, 1, 2],
        [8, 8, 8]])


In [9]:
#How would you normalize a tensor using min-max scaling?
min_val = torch.min(tensor)
max_val = torch.max(tensor)
normalized_tensor = (tensor - min_val) / (max_val - min_val)
print(normalized_tensor)


tensor([[0.2500, 0.7500, 0.0000],
        [0.5000, 0.1250, 0.8750],
        [1.0000, 0.6250, 0.3750]])
